# -*- coding: utf-8 -*-
"""Personal simple RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rR-h5GnKg6goj-NABTDc94Mr2z0k3wEY

# **Define LLM from openrouter**

---
"""

!pip install -qU langchain "langchain[openai]"
!pip install langchain-classic
!pip install -U langchain-community
!pip install python-dotenv

from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
import os

load_dotenv()
llm = ChatOpenAI(
    api_key=os.getenv("OPENAI_API_KEY"),
    base_url="https://openrouter.ai/api/v1",
    model="openrouter/free",
    temperature=0.8
)

"""# **Data Loading (CV, TXT, LInkedIn)**

Note: LinkedIn blocks scraping so we will download it manully and parse it.
"""

!pip install pypdf

from google.colab import files
import os

os.makedirs("data", exist_ok=True)

uploaded = files.upload()

for filename in uploaded.keys():

    with open(f"data/{filename}", "wb") as f:
        f.write(uploaded[filename])

docs = load_documents("data")

docs[0]

import re

def clean_text(text):

    text = re.sub(r'\s+', ' ', text)   # remove extra spaces
    text = re.sub(r'\n+', '\n', text)  # normalize new lines

    return text.strip()

def linkedin_structure(text):

    sections = {
        "contact": "",
        "skills": "",
        "experience": "",
        "education": ""
    }

    current = "experience"

    lines = text.split("\n")

    for line in lines:

        line = line.strip()

        if "Contact" in line:
            current = "contact"

        elif "Top Skills" in line:
            current = "skills"

        elif "Experience" in line:
            current = "experience"

        elif "Education" in line:
            current = "education"

        sections[current] += line + " "

    return sections

from langchain_core.documents import Document

def to_documents(sections):

    docs = []

    for section, value in sections.items():

        if value.strip():

            docs.append(
                Document(
                    page_content=value,
                    metadata={"source": "linkedin", "section": section}
                )
            )

    return docs

from langchain_community.document_loaders import TextLoader
from langchain_community.document_loaders import PyPDFLoader
import os


def load_all_data(data_folder="data"):

    all_docs = []

    for file in os.listdir("data"):

        path = os.path.join("data", file)

        # TXT FILES (CV / LIFE STORY)
        if file.endswith(".txt"):

            loader = TextLoader(path, encoding="utf-8")
            all_docs.extend(loader.load())

        # PDF FILES (LinkedIn)
        elif file.endswith(".pdf"):

            loader = PyPDFLoader(path)
            pdf_docs = loader.load()

            full_text = " ".join([d.page_content for d in pdf_docs])

            cleaned = clean_text(full_text)

            structured = linkedin_structure(cleaned)

            linkedin_docs = to_documents(structured)

            all_docs.extend(linkedin_docs)

    return all_docs

docs = load_all_data()

print(len(docs))
print(docs[2].page_content)

"""# **Chunking**"""

# Chunking
from langchain_classic.text_splitter import TokenTextSplitter

splitter = TokenTextSplitter(
        chunk_size = 100,
        chunk_overlap = 10
)

chunks = splitter.split_documents(docs)

chunks

"""# **Embeding**"""

# Embedding
from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
        model_name = "sentence-transformers/all-MiniLM-L6-v2",
        model_kwargs = {"device":"cpu"}
)

vectors = embeddings.embed_documents([i.page_content for i in chunks])

"""# FAISS vector store"""

!pip install faiss-cpu

# vector store
from langchain_classic.vectorstores import FAISS

vectorDB = FAISS.from_documents(chunks,embeddings)

def retrieve_context(vectorDB, query):

    docs = vectorDB.similarity_search(query, k=4)

    # Combine retrieved text
    context = "\n".join([d.page_content for d in docs])

    return context

query = "Who is this person?"
context = retrieve_context(vectorDB, query)

context

"""# **Memory**"""

# define converstion
from langchain_classic.chains import ConversationChain
from langchain_classic.memory import ConversationBufferMemory

chat_memory = ConversationChain(
    llm = llm,
    memory = ConversationBufferMemory(
        memory_key="history", #Defines the dictionary key used to pass the saved dialogue
        return_messages=True #Extracts past conversation turns as distinct objects (like HumanMessage and AIMessage) rather than flattening them into a raw text string.
    )
)

response = chat_memory.predict(input="who Iam ?")

def get_history():

    return chat_memory.memory.load_memory_variables({})["history"]

response

"""# **prompt Engineering**"""

from langchain_core.prompts import PromptTemplate

temp = """
you are assistant, Answer the next Question using provided context,
If you don't know the answer, just say you don't know.
answer should be within 30 words or lower only.
Answer in {language}.

## context :
{context}

## Chat History:
{history}

## Question :
{Question}

"""

temp = PromptTemplate.from_template(temp)


query1 = "Who is this person?"
query2= "What are his skills?"
query3= "What projects did he work on?"
query4= "What are his interests?"
query5= "Summarize his career."
history = get_history()
context = retrieve_context(vectorDB, query)



prompt = temp.format(
    context=context,
    Question=query1,
    history=history,
    language="arabic"
)
print(prompt)

response = llm.invoke(prompt).content

from IPython.display import display , Markdown

display(Markdown(response))